### ISSUE TITLE
Login with JWT authentication, not just Basic Authentication.

### ISSUE THREAD

**Issue by haturatu** [lumeland/cms#21]
I really like LumeCMS.

While Basic auth is sufficient, are there any plans for implementing JWT auth in the roadmap?

I've managed to implement it myself. Being able to do so might broaden its usability.

I don't want to disrupt the simplicity and lightweight nature of LumeCMS. Instead, I made it possible to select JWT auth by adding
```
  auth: {
    method: "jwt",
  },
```
![image](https://github.com/user-attachments/assets/fe913215-7bfe-46f2-b405-201112aaa4e3)

However, it's clear that the code is not in a state for a pull request as it's currently a personal project.

What I want to know is
- For integration, would it be aesthetically pleasing to place the JWT login page file under the cms/server directory?
- Is it acceptable (from a web development perspective) to run the JWT auth page on port 8787 and then POST the auth token to port 8000?

thank you

**Comment by oscarotero** [comment]
For now, I'm not planning to include other auth methods because they introduce some complexity. The benefits of Basic auth is that it works out of the box, because the session persitence is handled by the browser. No need to create cookies, login pages, tokens or anything like that.

I'd like to have other methods in the future (and maybe JWT would be a nice addition) but for now I would like to focus in other aspects of the CMS.

That being said, if you know a simple way to add support for JWT without change too much code, I can take a look to your proposal. To be honest, I'm not an expert of implementing auth methods.

The use of different ports to send tokens is not an option because this CMS is intended to work on hosting servers (like Deno Deploy) where you cannot choose the ports to use.

**Comment by haturatu** [comment]
That's true. Adding more complexity goes against the principle of "Small is beautiful." ( I like the UNIX philosophy.)Especially in the current situation, having a system that works well within this small codebase feels very comfortable.

Therefore, if we were to implement something new, I believe it would succeed if it functions as a modular component without making significant changes to the existing code.

Thank you for explaining the design considerations for Deno Deploy.
Go Lume!
